### ISSUE TITLE
File manager: add ability to move a file

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#798]
If a file is uploaded to the wrong place, at present you have to delete it and upload again. Would be better if a selected file could be moved to a destination folder.

**Comment by SimonAnnetts** [comment]
@CrispinF 
One problem I forsee in this is that a file maybe moved in the file manager and it will break a hyperlink on a simplecontent page. The filemanager does not know if any file is currently being linked to in any content.

**Comment by markidox** [comment]
There is a PR for this. The work provides users with a button to move a file using the file manager. It will physically move the file on the file system but will not then search for instances within cloudscribe and update the URLs as it stands.

**Comment by JimKerslake** [comment]
Holding off merging this one to the 8.1 dev branch for now... possibly some outstanding issues still to work on.
Wait til v8.2...


> It would be possible to see whether the file has been used in content, and indeed to update the usages with the new location. Once the file has been moved, this is a mechanistic find and replace operation. Any reason not to do this? Blog posts and pages (plus their drafts) would be the places to look. Any reason not to do this?

Possible in principle. though in practice... a few complications.
Need to bear in mind that the page content in cs_Page:
1. can be authored in either html or markdown 
2. is not only held in the content field - but is also serialized into the fields serialized_model and draft_serialized_model
3. ...and the serializer used for the latter is also customisable - not necessarily always JSON.

So if you were trying for some kind of regex replace direct onto the database (would need to be implemented separately for each supported Db type), you'd need to be dealing with this kind of content... HTML (or MD) serialised inside of JSON... quite a high risk of corrupting that and ending up with a page template that is just broken.

`{"ContentAbove":"<style type=\"text/css\">#button {\r\nbackground-color:rgb(158,45,50);\r\ncolor:rgb(254,211,0);\r\n}\r\n#button:hover {\r\nbackground-color:rgb(130,25,30);\r\ncolor:rgb(255,255,255);\r\n}\r\n</style>\r\n<div class=\"row\">\r\n<div class=\"col-4 col-sm-3\"><img alt=\"Works Commissioner logo\" src=\"/documents_and_alerts/thumbnails/srwc-logo-345-155.png\" style=\"min-width:60px;max-width:76px;margin:0.5em;\" /></div>\r\n\r\n<div class=\"col-12 col-lg-8 mt-sm-2\">\r\n<h4 class=\"card-title ml-2 ml-lg-0\"><a href=\"https://roadworks.scot/home\" target=\"_blank\" title=\"Roads Authorities &amp; Utilities Committee (Scotland)\">Roads Authorities &amp; Utilities Committee (Scotland)</a></h4>\r\n<!-- <p class=\"text-muted ml-2 ml-lg-0\">The Scottish Road Works Commissioner oversees improvements to the planning, co-ordination and quality of road works in Scotland.</p> --></div>\r\n</div>\r\n</div>\r\n<!-- end item card --><!-- start card -->\r\n\r\n<div class=\"card border-primary mb-2 mb-md-4\">\r\n<div class=\"row\">\r\n<div class=\"col-4 col-sm-3\"><img alt=\"Welsh logo\" src=\"https://app.mydomain-uk.org.uk/media/images/alertsdocuments/wlogo.jpg\" style=\"min-width:60px;max-width:76px;margin:0.5em;\" /></div>\r\n\r\n<div class=\"col-12 col-lg-8 mt-sm-2\">\r\n<h4 class=\"card-title ml-2 ml-lg-0  mt-2\"><a href=\"http://www.w.com/site/\" target=\"_blank\" title=\"Welsh site\">Welsh site</a></h4>\r\n<!-- <p class=\"text-muted ml-2 ml-lg-0\">Descriptive text</p> --></div>\r\n</div>\r\n</div>\r\n<!-- end item card --></div>\r\n<!-- end card deck -->\r\n\r\n`

**Comment by JimKerslake** [comment]
I don't think this is ever going to work (except locally!) 
 
![Image](https://github.com/user-attachments/assets/6c534fbc-d8ae-4d34-9d75-db0014598e19)

Would very much prefer to avoid reintroducing inline <script> blocks (for CSP reasons), 
and also would prefer a more meaningful file name, not the appended '2'

Need to reference the js file via  <script src="~/filemanager/js/ 

I'll footle around with this feature branch myself for a while...

**Comment by markidox** [comment]
Ah sorry. Thought I'd caught everything that I'd been doing to get it to work...I guess not!
I couldn't get the JQuery to fire just pulling the file in itself, though maybe the onload check can go in the file?

**Comment by JimKerslake** [comment]
I'll play around and see how it goes (probably get myself into an almighty mess ;) 
- I'd prefer to get rid of all these '2's also and use something more descriptive like _movefile 

![Image](https://github.com/user-attachments/assets/6be17dd0-3e7e-4543-9a31-030ffc701d11)

I get the idea of what you're doing though...
I think I'll add some kind of event handler trigger to the controller move action so we can potentially hook in other server-side stuff to respond to the file move.

**Comment by JimKerslake** [comment]
Yeah looks a bit broken in a tenant site - never ends does it?  ;) 

![Image](https://github.com/user-attachments/assets/664599d5-76a5-4087-9275-5cbad10b08da)

**Comment by JimKerslake** [comment]
Assuming it all works OK, we'll have an IHandleFileMoved hook, so we can implement event handlers wherever we like (eg over in SimpleContent) to respond to a File Moved event like this:

![Image](https://github.com/user-attachments/assets/015399b0-da4e-4387-a652-0fbe05efd67a)

So from that hook we could perhaps have a go at updating URLs in stored page content.

**Comment by JimKerslake** [comment]
OK I've fixed quite a few issues with this...

There remain two issues that would be nice to fix but perhaps not essential.

1 - although we are bundling and releasing a copy of  cloudscribe-filemanager.min.js  that is seemingly not getting used anywhere - we just use the unminified version.    The same is now true of the new equivalent filemover.js 
We ought to swap to using minified versions sometime (perhaps when  filemover.js and filemanager.js are both done and dusted and stable).

2 - when you make a new sub-folder in the main file manager UI, and then use the Move File UI, the treeview in the modal (Select Folder To Move File To) will not display your new sub-folder until after a page reload.  Feels like the base filemanager.js needs to have some way to re-populate the data attribute that stores the current folder tree for filemover.js to consume... or some kind of equivalent DOM reload needs to happen anyway.

**Comment by JimKerslake** [comment]
OK again - have fixed the second issue above now I think - 
Will get this pushed through to testing 'develop' branch now.

**Comment by JimKerslake** [comment]
Spoke too soon again - it doesn't work from the 'browse server' modal that is invoked from the simplecontent editor insert-image toolbar button

![Image](https://github.com/user-attachments/assets/bd5a4039-8015-479b-ac4c-8006c9159a68)

(Never ends does it...)

**Comment by markidox** [comment]
As in from CKEditor? It did do, this was the main place I tested it.

Also, I'd had the treeview refreshing when you had moved something previously for exactly the reason you mentioned before (it still showing in the old folder). I could only manage to reload it it so not bring the user back to the same folder or the new folder.

**Comment by JimKerslake** [comment]
So if we want to have a bash at handling a file move by updating pages and posts - that'll need to be a new ticket over in SimpleContent.  See event handler strategy above. 

Remembering that any such change needs to include a tenant Id constraint against the pages / posts to work on, because the physical path to a file URL like "images/logo.png" will vary between tenants - so a different file of the same name may exist in both tenants in different physical paths but seeming to have the same relative URL in the page HTML. That's why the tenant Id is there in the event handler definition.
